version: '3'

services:

  backend:
    build: ../ecommerce-backend/ecommerce-backend-node
    ports:
      - "3000:3000"
    container_name: ecommerce-backend

  frontend:
    build: ../ecommers-frontend/shop
    ports:
      - "4200:80"
    container_name: ecommerce-frontend
    depends_on:
      - backend